apiVersion: apps/v1
kind: Deployment
metadata:
    name: Helloword--deployment
    #namespace: demo
spec:
    replicas: 1
    selector:
        matchLabels:
            env: test
    template:
        metadata:
            labels:
                env: test
        spec:
            containers:
                - name: calsoft
                  image: shubh9975/simple-app:v3
                  #image: nginx
                 
---
apiVersion: v1
kind: Service
metadata:
    name: calsoft-service
    #namespace: calsoft
spec:
    type: NodePort
    ports:
        - port: 80
          nodePort: 31488
    selector:
        env: test
